# Generated by Django 5.2.7 on 2026-01-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
